name: "Infinitude"
description: "Infinitude can also optionally monitor the Carrier/Bryant RS485(ABCD) bus to obtain higher resolution access to values within your thermostat, air handler, heat pump, and other devices. Infinitude provides a serial monitor which keeps track of the current state of registers on the serial bus, and highlights changing bytes to aid in protocol analysis. Serial data can be monitored via an attached serial port or via a networked serial bridge."
version: "1.0.0"
slug: "infinitude"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386